//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Acme.Module.BusinessObjects.acme
{

    public partial class BusinessUnit : BaseObject
    {
        [Association(@"ServiceReferencesBusinessUnit")]
        public XPCollection<Service> Services { get { return GetCollection<Service>("Services"); } }
    }

}
