//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Acme.Module.BusinessObjects.acme
{

    public partial class Service : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        BusinessUnit fBusinessUnit;
        [Association(@"ServiceReferencesBusinessUnit")]
        public BusinessUnit BusinessUnit
        {
            get { return fBusinessUnit; }
            set { SetPropertyValue<BusinessUnit>("BusinessUnit", ref fBusinessUnit, value); }
        }
        ServiceType fServiceType;
        [Association(@"ServiceReferencesServiceType")]
        public ServiceType ServiceType
        {
            get { return fServiceType; }
            set { SetPropertyValue<ServiceType>("ServiceType", ref fServiceType, value); }
        }
        ServiceLocation fServiceLocation;
        [Association(@"ServiceReferencesServiceLocation")]
        public ServiceLocation ServiceLocation
        {
            get { return fServiceLocation; }
            set { SetPropertyValue<ServiceLocation>("ServiceLocation", ref fServiceLocation, value); }
        }
        Period fPeriod;
        [Association(@"ServiceReferencesPeriod")]
        public Period Period
        {
            get { return fPeriod; }
            set { SetPropertyValue<Period>("Period", ref fPeriod, value); }
        }
        [Association(@"UserServiceReferencesService")]
        public XPCollection<UserService> UserServices { get { return GetCollection<UserService>("UserServices"); } }
        [Association(@"AppServiceReferencesService")]
        public XPCollection<AppService> AppServices { get { return GetCollection<AppService>("AppServices"); } }
    }

}
