//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Acme.Module.BusinessObjects.acme
{

    public partial class UserService : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        Department fDepartment;
        [Association(@"UserServiceReferencesDepartment")]
        public Department Department
        {
            get { return fDepartment; }
            set { SetPropertyValue<Department>("Department", ref fDepartment, value); }
        }
        string fAgency;
        public string Agency
        {
            get { return fAgency; }
            set { SetPropertyValue<string>("Agency", ref fAgency, value); }
        }
        string fCount;
        public string Count
        {
            get { return fCount; }
            set { SetPropertyValue<string>("Count", ref fCount, value); }
        }
        [Association(@"UserServiceReferencesService")]
        public XPCollection<Service> Services { get { return GetCollection<Service>("Services"); } }
    }

}
